# Generated by Django 4.2.19 on 2025-03-11 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salespersons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='notes',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='bio',
            field=models.TextField(default='no bio...'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='username',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
