# Generated by Django 4.2.19 on 2025-03-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0002_remove_salesperson_name_remove_salesperson_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='name',
            field=models.CharField(default='Unknown Salesperson', max_length=120),
            preserve_default=False,
        ),
    ]
