# Generated by Django 4.2.19 on 2025-03-12 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salespersons', '0004_alter_salesperson_name_alter_salesperson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='bio',
            field=models.TextField(default='No bio...'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesperson', to=settings.AUTH_USER_MODEL),
        ),
    ]
