# Generated by Django 4.2.19 on 2025-03-11 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_notes_book_book_type_book_genre_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='notes',
        ),
        migrations.AddField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(default=sales.models.get_default_book, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=9.99),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
